version: "3.9"

services:
  selenium:
    image: selenium/standalone-chromium:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - .:/app
    working_dir: /app
